name: Build on update branch changes

#on:
 # push:
  #  branches:
   #   - satish
  pull_request:
    branches:
      - update

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Build Commands
        run: |
          echo "Build triggered due to changes in the update branch"
          # Add your actual build steps here
